<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="vehicle">

    <xacro:include filename="inertial_box.urdf.xacro"/>
    <xacro:include filename="inertial_cylinder.urdf.xacro"/>
    <xacro:include filename="inertial_sphere.urdf.xacro"/>
    <xacro:include filename="wheel.urdf.xacro"/>

    <!-- Inputs -->

    <xacro:property name="chassis_size_x" value="1.0" />
    <xacro:property name="chassis_size_y" value="0.5" />
    <xacro:property name="chassis_size_z" value="0.15" />
    <xacro:property name="chassis_mass" value="1.0" />

    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="wheel_mass" value="0.5" />

    <xacro:property name="caster_radius" value="0.1" />
    <xacro:property name="caster_mass" value="0.0415553" />

    <!-- Calculated properties -->
    <xacro:property name="wheel_x_offset" value="${chassis_size_x * 0.3}" />
    <xacro:property name="wheel_y_offset" value="${(chassis_size_y + wheel_length) * 0.5}" />
    <xacro:property name="wheel_z_offset" value="${-wheel_radius * 0.5}" />

    <xacro:property name="caster_x_offset" value="${-chassis_size_x * 0.3}" />
    <xacro:property name="caster_y_offset" value="0" />
    <xacro:property name="caster_z_offset" value="${-(chassis_size_z + caster_radius) * 0.5}" />

    <material name="grey">
        <color rgba="0.8 0.8 0.8 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <link name="chassis">
        <visual>
            <geometry>
                <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box
          mass="${chassis_mass}"
          x="${chassis_size_x}"
          y="${chassis_size_y}"
          z="${chassis_size_z}"/>
    </link>

    <xacro:wheel side="left"/>
    <xacro:wheel side="right"/>

    <!-- caster -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_x_offset} ${caster_y_offset} ${caster_z_offset}"/>
    </joint>
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere
          mass="${caster_mass}"
          radius="${caster_radius}"/>
    </link>

</robot>
